language: scala
jdk: oraclejdk8
script: 
  - sbt dist
deploy:
  - provider: boxfuse
    user: $user
    secret: $secret
    env: prod
    envvars.DB_USERNAME = $DB_USERNAME
    envvars.DB_PASSWORD = $DB_PASSWORD
    envvars.DB_DRIVER = $DB_DRIVER
    envvars.DB_URL = $REST_PORT
    on:
      branch: master
  - provider: boxfuse
    user: $user
    secret: $secret
    env: test
    envvars.DB_USERNAME = $DB_USERNAME
    envvars.DB_PASSWORD = $DB_PASSWORD
    envvars.DB_DRIVER = $DB_DRIVER
    envvars.DB_URL = $DB_URL_DEV
    envvars.REST_PORT = $REST_PORT
    on:
      branch: develop
# Use container-based infrastructure
sudo: false
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
