language: scala
jdk: oraclejdk8
# safelist
branches:
  only:
  - master
  - develop
script:
  - sbt dist
deploy:
  - provider: boxfuse
    user: $user
    secret: $secret
    env: prod
    extra_args: "-envvars.DB_USERNAME=$DB_USERNAME -envvars.DB_PASSWORD=$DB_PASSWORD -envvars.DB_DRIVER=$DB_DRIVER -envvars.REST_PORT=$REST_PORT -envvars.DB_URL=$DB_URL"
    image: "genserver:$TRAVIS_BUILD_NUMBER"
    on:
      branch: master
  - provider: boxfuse
    user: $user
    secret: $secret
    env: test
    extra_args: "-envvars.DB_USERNAME=$DB_USERNAME -envvars.DB_PASSWORD=FUCKYOU -envvars.DB_DRIVER=$DB_DRIVER -envvars.REST_PORT=$REST_PORT -envvars.DB_URL=$DB_URL_DEV"
    image: "genserver:$TRAVIS_BUILD_NUMBER"
    on:
      branch: develop
# Use container-based infrastructure
sudo: false
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
